In [ ]:
#CLEAN ONE FILE


import csv

def manual_csv_cleaner_with_rename(input_file, output_file, skip_rows=215, error_row=447):
    """
    Manual CSV cleaning that:
    - Skips initial rows
    - Handles error row
    - Renames first column to NAME_0
    """
    cleaned_rows = []
    
    with open(input_file, 'r', encoding='utf-8', errors='ignore') as f:
        reader = csv.reader(f)
        
        # Skip initial garbage rows
        for _ in range(skip_rows):
            next(reader)
        
        # Read until error row
        for i, row in enumerate(reader):
            if skip_rows + i >= error_row - 1:
                break
            cleaned_rows.append(row)
        
        # Skip the problematic row and continue
        for row in reader:
            cleaned_rows.append(row)
    
    # Rename first column in header row if it exists
    if len(cleaned_rows) > 0:
        if cleaned_rows[0]:  # Check if header row exists
            cleaned_rows[0][0] = 'NAME_0'  # Rename first column
    
    # Write cleaned data
    with open(output_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(cleaned_rows)
    
    print(f"Cleaned data with renamed column saved to {output_file}")

# Usage example
manual_csv_cleaner_with_rename(
    input_file="Datasets/GC_test/2022_ndvi.csv",
    output_file="clean4.csv",
    skip_rows=215,
    error_row=447
)

Cleaned data with renamed column saved to clean4.csv

In [ ]:
# BATCH CLEANING


import os
import csv
import re

def clean_rainfall_files_preserve_columns(input_dir='Datasets/GC_test', output_dir='Datasets/GC_testRefined'):
    """
    Processes all *_rainfall.csv files while preserving column names:
    - Skips first 216 rows
    - Handles row 447 error
    - Renames ONLY first column to NAME_0
    - Preserves all other column names
    - Saves as newYYYY_rainfall.csv
    """
    # Create output directory if needed
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all matching files
    lst_files = [f for f in os.listdir(input_dir) if f.endswith('_rainfall.csv')]
    
    if not lst_files:
        print("No *_rainfall.csv files found in directory")
        return
    
    print(f"Found {len(lst_files)} files to process")
    
    for input_file in lst_files:
        try:
            # Extract year from filename
            year_match = re.search(r'(\d{4})_rainfall\.csv$', input_file)
            year = year_match.group(1) if year_match else "unknown"
            output_file = f"new{year}_rainfall.csv"
            output_path = os.path.join(output_dir, output_file)
            
            print(f"\nProcessing {input_file} -> {output_file}")
            
            # Read original header (row 216)
            with open(os.path.join(input_dir, input_file), 'r', encoding='utf-8', errors='ignore') as f:
                reader = csv.reader(f)
                for _ in range(216):  # Skip to row 216
                    header = next(reader)
            
            # Process data rows
            cleaned_rows = []
            with open(os.path.join(input_dir, input_file), 'r', encoding='utf-8', errors='ignore') as f:
                reader = csv.reader(f)
                
                # Skip initial 216 rows
                for _ in range(216):
                    next(reader)
                
                # Read until error row (447 total - 216 skipped = row 196 in reader)
                for i, row in enumerate(reader):
                    if i >= 196 - 1:  # Because we already skipped 216
                        break
                    cleaned_rows.append(row)
                
                # Skip the problematic row and continue
                next(reader)  # Skip the bad row
                for row in reader:
                    cleaned_rows.append(row)
            
            # Modify ONLY the first column name
            if header:
                new_header = list(header)
                new_header[0] = 'NAME_0'  # Only change first column
                cleaned_rows.insert(0, new_header)  # Reinsert header at start
            
            # Write cleaned data
            with open(output_path, 'w', newline='') as f:
                writer = csv.writer(f)
                writer.writerows(cleaned_rows)
            
            print(f"Successfully processed {input_file}")
            print(f"Original columns: {header}")
            print(f"Modified columns: {new_header}")
            
        except Exception as e:
            print(f"Error processing {input_file}: {str(e)}")
    
    print("\nBatch processing complete!")

# Usage
clean_rainfall_files_preserve_columns(input_dir='Datasets/GC_test')

Found 4 files to process

Processing 2022_rainfall.csv -> new2022_rainfall.csv
Successfully processed 2022_rainfall.csv
Original columns: ['NAME_0', 'NAME_1', 'NAME_2', 'ID_2', 'Mean_RAINFALL_2022.01.01[mm]', 'Mean_RAINFALL_2022.01.02[mm]', 'Mean_RAINFALL_2022.01.03[mm]', 'Mean_RAINFALL_2022.01.04[mm]', 'Mean_RAINFALL_2022.01.05[mm]', 'Mean_RAINFALL_2022.01.06[mm]', 'Mean_RAINFALL_2022.01.07[mm]', 'Mean_RAINFALL_2022.01.08[mm]', 'Mean_RAINFALL_2022.01.09[mm]', 'Mean_RAINFALL_2022.01.10[mm]', 'Mean_RAINFALL_2022.01.11[mm]', 'Mean_RAINFALL_2022.01.12[mm]', 'Mean_RAINFALL_2022.01.13[mm]', 'Mean_RAINFALL_2022.01.14[mm]', 'Mean_RAINFALL_2022.01.15[mm]', 'Mean_RAINFALL_2022.01.16[mm]', 'Mean_RAINFALL_2022.01.17[mm]', 'Mean_RAINFALL_2022.01.18[mm]', 'Mean_RAINFALL_2022.01.19[mm]', 'Mean_RAINFALL_2022.01.20[mm]', 'Mean_RAINFALL_2022.01.21[mm]', 'Mean_RAINFALL_2022.01.22[mm]', 'Mean_RAINFALL_2022.01.23[mm]', 'Mean_RAINFALL_2022.01.24[mm]', 'Mean_RAINFALL_2022.01.25[mm]', 'Mean_RAINFALL_2022.01.26[mm]', 'Mean_RAINFALL_2022.01.27[mm]', 'Mean_RAINFALL_2022.01.28[mm]', 'Mean_RAINFALL_2022.01.29[mm]', 'Mean_RAINFALL_2022.01.30[mm]', 'Mean_RAINFALL_2022.01.31[mm]', 'Mean_RAINFALL_2022.02.01[mm]', 'Mean_RAINFALL_2022.02.02[mm]', 'Mean_RAINFALL_2022.02.03[mm]', 'Mean_RAINFALL_2022.02.04[mm]', 'Mean_RAINFALL_2022.02.05[mm]', 'Mean_RAINFALL_2022.02.06[mm]', 'Mean_RAINFALL_2022.02.07[mm]', 'Mean_RAINFALL_2022.02.08[mm]', 'Mean_RAINFALL_2022.02.09[mm]', 'Mean_RAINFALL_2022.02.10[mm]', 'Mean_RAINFALL_2022.02.11[mm]', 'Mean_RAINFALL_2022.02.12[mm]', 'Mean_RAINFALL_2022.02.13[mm]', 'Mean_RAINFALL_2022.02.14[mm]', 'Mean_RAINFALL_2022.02.15[mm]', 'Mean_RAINFALL_2022.02.16[mm]', 'Mean_RAINFALL_2022.02.17[mm]', 'Mean_RAINFALL_2022.02.18[mm]', 'Mean_RAINFALL_2022.02.19[mm]', 'Mean_RAINFALL_2022.02.20[mm]', 'Mean_RAINFALL_2022.02.21[mm]', 'Mean_RAINFALL_2022.02.22[mm]', 'Mean_RAINFALL_2022.02.23[mm]', 'Mean_RAINFALL_2022.02.24[mm]', 'Mean_RAINFALL_2022.02.25[mm]', 'Mean_RAINFALL_2022.02.26[mm]', 'Mean_RAINFALL_2022.02.27[mm]', 'Mean_RAINFALL_2022.02.28[mm]', 'Mean_RAINFALL_2022.03.01[mm]', 'Mean_RAINFALL_2022.03.02[mm]', 'Mean_RAINFALL_2022.03.03[mm]', 'Mean_RAINFALL_2022.03.04[mm]', 'Mean_RAINFALL_2022.03.05[mm]', 'Mean_RAINFALL_2022.03.06[mm]', 'Mean_RAINFALL_2022.03.07[mm]', 'Mean_RAINFALL_2022.03.08[mm]', 'Mean_RAINFALL_2022.03.09[mm]', 'Mean_RAINFALL_2022.03.10[mm]', 'Mean_RAINFALL_2022.03.11[mm]', 'Mean_RAINFALL_2022.03.12[mm]', 'Mean_RAINFALL_2022.03.13[mm]', 'Mean_RAINFALL_2022.03.14[mm]', 'Mean_RAINFALL_2022.03.15[mm]', 'Mean_RAINFALL_2022.03.16[mm]', 'Mean_RAINFALL_2022.03.17[mm]', 'Mean_RAINFALL_2022.03.18[mm]', 'Mean_RAINFALL_2022.03.19[mm]', 'Mean_RAINFALL_2022.03.20[mm]', 'Mean_RAINFALL_2022.03.21[mm]', 'Mean_RAINFALL_2022.03.22[mm]', 'Mean_RAINFALL_2022.03.23[mm]', 'Mean_RAINFALL_2022.03.24[mm]', 'Mean_RAINFALL_2022.03.25[mm]', 'Mean_RAINFALL_2022.03.26[mm]', 'Mean_RAINFALL_2022.03.27[mm]', 'Mean_RAINFALL_2022.03.28[mm]', 'Mean_RAINFALL_2022.03.29[mm]', 'Mean_RAINFALL_2022.03.30[mm]', 'Mean_RAINFALL_2022.03.31[mm]', 'Mean_RAINFALL_2022.04.01[mm]', 'Mean_RAINFALL_2022.04.02[mm]', 'Mean_RAINFALL_2022.04.03[mm]', 'Mean_RAINFALL_2022.04.04[mm]', 'Mean_RAINFALL_2022.04.05[mm]', 'Mean_RAINFALL_2022.04.06[mm]', 'Mean_RAINFALL_2022.04.07[mm]', 'Mean_RAINFALL_2022.04.08[mm]', 'Mean_RAINFALL_2022.04.09[mm]', 'Mean_RAINFALL_2022.04.10[mm]', 'Mean_RAINFALL_2022.04.11[mm]', 'Mean_RAINFALL_2022.04.12[mm]', 'Mean_RAINFALL_2022.04.13[mm]', 'Mean_RAINFALL_2022.04.14[mm]', 'Mean_RAINFALL_2022.04.15[mm]', 'Mean_RAINFALL_2022.04.16[mm]', 'Mean_RAINFALL_2022.04.17[mm]', 'Mean_RAINFALL_2022.04.18[mm]', 'Mean_RAINFALL_2022.04.19[mm]', 'Mean_RAINFALL_2022.04.20[mm]', 'Mean_RAINFALL_2022.04.21[mm]', 'Mean_RAINFALL_2022.04.22[mm]', 'Mean_RAINFALL_2022.04.23[mm]', 'Mean_RAINFALL_2022.04.24[mm]', 'Mean_RAINFALL_2022.04.25[mm]', 'Mean_RAINFALL_2022.04.26[mm]', 'Mean_RAINFALL_2022.04.27[mm]', 'Mean_RAINFALL_2022.04.28[mm]', 'Mean_RAINFALL_2022.04.29[mm]', 'Mean_RAINFALL_2022.04.30[mm]', 'Mean_RAINFALL_2022.05.01[mm]', 'Mean_RAINFALL_2022.05.02[mm]', 'Mean_RAINFALL_2022.05.03[mm]', 'Mean_RAINFALL_2022.05.04[mm]', 'Mean_RAINFALL_2022.05.05[mm]', 'Mean_RAINFALL_2022.05.06[mm]', 'Mean_RAINFALL_2022.05.07[mm]', 'Mean_RAINFALL_2022.05.08[mm]', 'Mean_RAINFALL_2022.05.09[mm]', 'Mean_RAINFALL_2022.05.10[mm]', 'Mean_RAINFALL_2022.05.11[mm]', 'Mean_RAINFALL_2022.05.12[mm]', 'Mean_RAINFALL_2022.05.13[mm]', 'Mean_RAINFALL_2022.05.14[mm]', 'Mean_RAINFALL_2022.05.15[mm]', 'Mean_RAINFALL_2022.05.16[mm]', 'Mean_RAINFALL_2022.05.17[mm]', 'Mean_RAINFALL_2022.05.18[mm]', 'Mean_RAINFALL_2022.05.19[mm]', 'Mean_RAINFALL_2022.05.20[mm]', 'Mean_RAINFALL_2022.05.21[mm]', 'Mean_RAINFALL_2022.05.22[mm]', 'Mean_RAINFALL_2022.05.23[mm]', 'Mean_RAINFALL_2022.05.24[mm]', 'Mean_RAINFALL_2022.05.25[mm]', 'Mean_RAINFALL_2022.05.26[mm]', 'Mean_RAINFALL_2022.05.27[mm]', 'Mean_RAINFALL_2022.05.28[mm]', 'Mean_RAINFALL_2022.05.29[mm]', 'Mean_RAINFALL_2022.05.30[mm]', 'Mean_RAINFALL_2022.05.31[mm]', 'Mean_RAINFALL_2022.06.01[mm]', 'Mean_RAINFALL_2022.06.02[mm]', 'Mean_RAINFALL_2022.06.03[mm]', 'Mean_RAINFALL_2022.06.04[mm]', 'Mean_RAINFALL_2022.06.05[mm]', 'Mean_RAINFALL_2022.06.06[mm]', 'Mean_RAINFALL_2022.06.07[mm]', 'Mean_RAINFALL_2022.06.08[mm]', 'Mean_RAINFALL_2022.06.09[mm]', 'Mean_RAINFALL_2022.06.10[mm]', 'Mean_RAINFALL_2022.06.11[mm]', 'Mean_RAINFALL_2022.06.12[mm]', 'Mean_RAINFALL_2022.06.13[mm]', 'Mean_RAINFALL_2022.06.14[mm]', 'Mean_RAINFALL_2022.06.15[mm]', 'Mean_RAINFALL_2022.06.16[mm]', 'Mean_RAINFALL_2022.06.17[mm]', 'Mean_RAINFALL_2022.06.18[mm]', 'Mean_RAINFALL_2022.06.19[mm]', 'Mean_RAINFALL_2022.06.20[mm]', 'Mean_RAINFALL_2022.06.21[mm]', 'Mean_RAINFALL_2022.06.22[mm]', 'Mean_RAINFALL_2022.06.23[mm]', 'Mean_RAINFALL_2022.06.24[mm]', 'Mean_RAINFALL_2022.06.25[mm]', 'Mean_RAINFALL_2022.06.26[mm]', 'Mean_RAINFALL_2022.06.27[mm]', 'Mean_RAINFALL_2022.06.28[mm]', 'Mean_RAINFALL_2022.06.29[mm]', 'Mean_RAINFALL_2022.06.30[mm]', 'Mean_RAINFALL_2022.07.01[mm]', 'Mean_RAINFALL_2022.07.02[mm]', 'Mean_RAINFALL_2022.07.03[mm]', 'Mean_RAINFALL_2022.07.04[mm]', 'Mean_RAINFALL_2022.07.05[mm]', 'Mean_RAINFALL_2022.07.06[mm]', 'Mean_RAINFALL_2022.07.07[mm]', 'Mean_RAINFALL_2022.07.08[mm]', 'Mean_RAINFALL_2022.07.09[mm]', 'Mean_RAINFALL_2022.07.10[mm]', 'Mean_RAINFALL_2022.07.11[mm]', 'Mean_RAINFALL_2022.07.12[mm]', 'Mean_RAINFALL_2022.07.13[mm]', 'Mean_RAINFALL_2022.07.14[mm]', 'Mean_RAINFALL_2022.07.15[mm]', 'Mean_RAINFALL_2022.07.16[mm]', 'Mean_RAINFALL_2022.07.17[mm]', 'Mean_RAINFALL_2022.07.18[mm]', 'Mean_RAINFALL_2022.07.19[mm]', 'Mean_RAINFALL_2022.07.20[mm]', 'Mean_RAINFALL_2022.07.21[mm]', 'Mean_RAINFALL_2022.07.22[mm]', 'Mean_RAINFALL_2022.07.23[mm]', 'Mean_RAINFALL_2022.07.24[mm]', 'Mean_RAINFALL_2022.07.25[mm]', 'Mean_RAINFALL_2022.07.26[mm]', 'Mean_RAINFALL_2022.07.27[mm]', 'Mean_RAINFALL_2022.07.28[mm]', 'Mean_RAINFALL_2022.07.29[mm]', 'Mean_RAINFALL_2022.07.30[mm]', 'Mean_RAINFALL_2022.07.31[mm]', 'Mean_RAINFALL_2022.08.01[mm]', 'Mean_RAINFALL_2022.08.02[mm]', 'Mean_RAINFALL_2022.08.03[mm]', 'Mean_RAINFALL_2022.08.04[mm]', 'Mean_RAINFALL_2022.08.05[mm]', 'Mean_RAINFALL_2022.08.06[mm]', 'Mean_RAINFALL_2022.08.07[mm]', 'Mean_RAINFALL_2022.08.08[mm]', 'Mean_RAINFALL_2022.08.09[mm]', 'Mean_RAINFALL_2022.08.10[mm]', 'Mean_RAINFALL_2022.08.11[mm]', 'Mean_RAINFALL_2022.08.12[mm]', 'Mean_RAINFALL_2022.08.13[mm]', 'Mean_RAINFALL_2022.08.14[mm]', 'Mean_RAINFALL_2022.08.15[mm]', 'Mean_RAINFALL_2022.08.16[mm]', 'Mean_RAINFALL_2022.08.17[mm]', 'Mean_RAINFALL_2022.08.18[mm]', 'Mean_RAINFALL_2022.08.19[mm]', 'Mean_RAINFALL_2022.08.20[mm]', 'Mean_RAINFALL_2022.08.21[mm]', 'Mean_RAINFALL_2022.08.22[mm]', 'Mean_RAINFALL_2022.08.23[mm]', 'Mean_RAINFALL_2022.08.24[mm]', 'Mean_RAINFALL_2022.08.25[mm]', 'Mean_RAINFALL_2022.08.26[mm]', 'Mean_RAINFALL_2022.08.27[mm]', 'Mean_RAINFALL_2022.08.28[mm]', 'Mean_RAINFALL_2022.08.29[mm]', 'Mean_RAINFALL_2022.08.30[mm]', 'Mean_RAINFALL_2022.08.31[mm]', 'Mean_RAINFALL_2022.09.01[mm]', 'Mean_RAINFALL_2022.09.02[mm]', 'Mean_RAINFALL_2022.09.03[mm]', 'Mean_RAINFALL_2022.09.04[mm]', 'Mean_RAINFALL_2022.09.05[mm]', 'Mean_RAINFALL_2022.09.06[mm]', 'Mean_RAINFALL_2022.09.07[mm]', 'Mean_RAINFALL_2022.09.08[mm]', 'Mean_RAINFALL_2022.09.09[mm]', 'Mean_RAINFALL_2022.09.10[mm]', 'Mean_RAINFALL_2022.09.11[mm]', 'Mean_RAINFALL_2022.09.12[mm]', 'Mean_RAINFALL_2022.09.13[mm]', 'Mean_RAINFALL_2022.09.14[mm]', 'Mean_RAINFALL_2022.09.15[mm]', 'Mean_RAINFALL_2022.09.16[mm]', 'Mean_RAINFALL_2022.09.17[mm]', 'Mean_RAINFALL_2022.09.18[mm]', 'Mean_RAINFALL_2022.09.19[mm]', 'Mean_RAINFALL_2022.09.20[mm]', 'Mean_RAINFALL_2022.09.21[mm]', 'Mean_RAINFALL_2022.09.22[mm]', 'Mean_RAINFALL_2022.09.23[mm]', 'Mean_RAINFALL_2022.09.24[mm]', 'Mean_RAINFALL_2022.09.25[mm]', 'Mean_RAINFALL_2022.09.26[mm]', 'Mean_RAINFALL_2022.09.27[mm]', 'Mean_RAINFALL_2022.09.28[mm]', 'Mean_RAINFALL_2022.09.29[mm]', 'Mean_RAINFALL_2022.09.30[mm]', 'Mean_RAINFALL_2022.10.01[mm]', 'Mean_RAINFALL_2022.10.02[mm]', 'Mean_RAINFALL_2022.10.03[mm]', 'Mean_RAINFALL_2022.10.04[mm]', 'Mean_RAINFALL_2022.10.05[mm]', 'Mean_RAINFALL_2022.10.06[mm]', 'Mean_RAINFALL_2022.10.07[mm]', 'Mean_RAINFALL_2022.10.08[mm]', 'Mean_RAINFALL_2022.10.09[mm]', 'Mean_RAINFALL_2022.10.10[mm]', 'Mean_RAINFALL_2022.10.11[mm]', 'Mean_RAINFALL_2022.10.12[mm]', 'Mean_RAINFALL_2022.10.13[mm]', 'Mean_RAINFALL_2022.10.14[mm]', 'Mean_RAINFALL_2022.10.15[mm]', 'Mean_RAINFALL_2022.10.16[mm]', 'Mean_RAINFALL_2022.10.17[mm]', 'Mean_RAINFALL_2022.10.18[mm]', 'Mean_RAINFALL_2022.10.19[mm]', 'Mean_RAINFALL_2022.10.20[mm]', 'Mean_RAINFALL_2022.10.21[mm]', 'Mean_RAINFALL_2022.10.22[mm]', 'Mean_RAINFALL_2022.10.23[mm]', 'Mean_RAINFALL_2022.10.24[mm]', 'Mean_RAINFALL_2022.10.25[mm]', 'Mean_RAINFALL_2022.10.26[mm]', 'Mean_RAINFALL_2022.10.27[mm]', 'Mean_RAINFALL_2022.10.28[mm]', 'Mean_RAINFALL_2022.10.29[mm]', 'Mean_RAINFALL_2022.10.30[mm]', 'Mean_RAINFALL_2022.10.31[mm]', 'Mean_RAINFALL_2022.11.01[mm]', 'Mean_RAINFALL_2022.11.02[mm]', 'Mean_RAINFALL_2022.11.03[mm]', 'Mean_RAINFALL_2022.11.04[mm]', 'Mean_RAINFALL_2022.11.05[mm]', 'Mean_RAINFALL_2022.11.06[mm]', 'Mean_RAINFALL_2022.11.07[mm]', 'Mean_RAINFALL_2022.11.08[mm]', 'Mean_RAINFALL_2022.11.09[mm]', 'Mean_RAINFALL_2022.11.10[mm]', 'Mean_RAINFALL_2022.11.11[mm]', 'Mean_RAINFALL_2022.11.12[mm]', 'Mean_RAINFALL_2022.11.13[mm]', 'Mean_RAINFALL_2022.11.14[mm]', 'Mean_RAINFALL_2022.11.15[mm]', 'Mean_RAINFALL_2022.11.16[mm]', 'Mean_RAINFALL_2022.11.17[mm]', 'Mean_RAINFALL_2022.11.18[mm]', 'Mean_RAINFALL_2022.11.19[mm]', 'Mean_RAINFALL_2022.11.20[mm]', 'Mean_RAINFALL_2022.11.21[mm]', 'Mean_RAINFALL_2022.11.22[mm]', 'Mean_RAINFALL_2022.11.23[mm]', 'Mean_RAINFALL_2022.11.24[mm]', 'Mean_RAINFALL_2022.11.25[mm]', 'Mean_RAINFALL_2022.11.26[mm]', 'Mean_RAINFALL_2022.11.27[mm]', 'Mean_RAINFALL_2022.11.28[mm]', 'Mean_RAINFALL_2022.11.29[mm]', 'Mean_RAINFALL_2022.11.30[mm]', 'Mean_RAINFALL_2022.12.01[mm]', 'Mean_RAINFALL_2022.12.02[mm]', 'Mean_RAINFALL_2022.12.03[mm]', 'Mean_RAINFALL_2022.12.04[mm]', 'Mean_RAINFALL_2022.12.05[mm]', 'Mean_RAINFALL_2022.12.06[mm]', 'Mean_RAINFALL_2022.12.07[mm]', 'Mean_RAINFALL_2022.12.08[mm]', 'Mean_RAINFALL_2022.12.09[mm]', 'Mean_RAINFALL_2022.12.10[mm]', 'Mean_RAINFALL_2022.12.11[mm]', 'Mean_RAINFALL_2022.12.12[mm]', 'Mean_RAINFALL_2022.12.13[mm]', 'Mean_RAINFALL_2022.12.14[mm]', 'Mean_RAINFALL_2022.12.15[mm]', 'Mean_RAINFALL_2022.12.16[mm]', 'Mean_RAINFALL_2022.12.17[mm]', 'Mean_RAINFALL_2022.12.18[mm]', 'Mean_RAINFALL_2022.12.19[mm]', 'Mean_RAINFALL_2022.12.20[mm]', 'Mean_RAINFALL_2022.12.21[mm]', 'Mean_RAINFALL_2022.12.22[mm]', 'Mean_RAINFALL_2022.12.23[mm]', 'Mean_RAINFALL_2022.12.24[mm]', 'Mean_RAINFALL_2022.12.25[mm]', 'Mean_RAINFALL_2022.12.26[mm]', 'Mean_RAINFALL_2022.12.27[mm]', 'Mean_RAINFALL_2022.12.28[mm]', 'Mean_RAINFALL_2022.12.29[mm]', 'Mean_RAINFALL_2022.12.30[mm]', 'Mean_RAINFALL_2022.12.31[mm]']

In [59]:
import numpy as np
import pandas as pd
# 'Datasets/GC_test/2020_ndvi.csv'
# 1. Load your data
file_path = 'Datasets/GC_testRefined/new2020_lst.csv'  # Change to your file path
df = pd.read_csv(file_path)
df

,NAME_0,NAME_1,NAME_2,GID_2,001MOD11A2,009MOD11A2,017MOD11A2,025MOD11A2,033MOD11A2,041MOD11A2,...,289MOD11A2,297MOD11A2,305MOD11A2,313MOD11A2,321MOD11A2,329MOD11A2,337MOD11A2,345MOD11A2,353MOD11A2,361MOD11A2
0,Malawi,Balaka,Balaka Town,MWI.1.1_1,29.465000,30.288000,28.972000,25.320000,27.020000,NaN,...,42.478000,41.844000,44.490000,38.314000,45.726000,43.454000,NaN,40.150000,36.032000,32.660000
1,Malawi,Balaka,TA Kalembo,MWI.1.2_1,28.482760,29.372533,27.290464,25.064527,27.016210,24.153786,...,45.430339,43.957365,46.688983,45.676749,48.365994,45.345871,30.506667,34.333951,34.127063,34.119168
2,Malawi,Balaka,TA Nsamala,MWI.1.3_1,28.709750,29.992200,27.741414,28.169891,26.065029,26.330080,...,45.129551,43.813111,44.708220,43.839634,47.837521,44.457088,31.045000,39.591624,36.006444,33.015878
3,Malawi,Blantyre,Blantyre City,MWI.2.1_1,24.961481,27.360127,27.347740,27.847087,24.310000,NaN,...,39.240048,36.473828,39.796220,37.254880,42.236220,40.496699,31.836667,32.345865,30.931124,26.708689
4,Malawi,Blantyre,TA Chigaru,MWI.2.2_1,30.762977,33.113333,26.623568,30.043964,27.558889,24.575333,...,45.425676,44.269369,45.923153,43.895586,47.066126,45.331351,31.490000,35.502153,38.075766,35.496126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241,Malawi,Thyolo,TA Nchilamwela,MWI.27.10_1,26.584375,26.502308,20.604872,26.684198,26.058571,25.467727,...,38.871258,34.704843,38.273145,37.876164,40.489119,39.344465,NaN,32.098931,31.955096,29.732105
242,Malawi,Thyolo,TA Nsabwe,MWI.27.11_1,NaN,31.413415,28.361650,29.977294,29.807273,27.873846,...,41.488058,40.082427,42.068835,45.073883,43.288058,41.423786,NaN,34.923010,33.184314,32.759216
243,Malawi,Thyolo,TA Thomas,MWI.27.12_1,27.148857,29.634255,23.398286,29.646383,26.219091,27.850000,...,39.986082,37.486082,42.215979,44.190206,42.541340,39.413505,NaN,34.079485,32.576598,30.449302
244,Malawi,Thyolo,Thyolo Boma,MWI.27.13_1,27.043333,NaN,NaN,25.350000,26.410000,NaN,...,38.816667,33.003333,40.010000,39.230000,39.630000,40.176667,NaN,32.823333,31.723333,NaN
245,Malawi,Zomba,Lake Chilwa,MWI.28.1_1,24.936026,25.243797,25.577630,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# 2. Melt the dataframe to long format
melted_df = pd.melt(
    df,
    id_vars=['NAME_0', 'NAME_1', 'NAME_2', 'GID_2'],  # Columns to keep as-is
    var_name='date_code',      # Name for new column holding the date codes
    value_name='lst_value'     # Name for new column holding the LST values
)

melted_df

#def combine_lst_datasets(input_dir='Datasets/GC_testRefined2', output_file='Datasets/GC_testRefined/combined_lst_data5.csv'):

       NAME_0    NAME_1          NAME_2        GID_2   date_code  lst_value
0      Malawi    Balaka     Balaka Town    MWI.1.1_1  001MOD11A2  29.465000
1      Malawi    Balaka      TA Kalembo    MWI.1.2_1  001MOD11A2  28.482760
2      Malawi    Balaka      TA Nsamala    MWI.1.3_1  001MOD11A2  28.709750
3      Malawi  Blantyre   Blantyre City    MWI.2.1_1  001MOD11A2  24.961481
4      Malawi  Blantyre      TA Chigaru    MWI.2.2_1  001MOD11A2  30.762977
...       ...       ...             ...          ...         ...        ...
11403  Malawi    Thyolo  TA Nchilamwela  MWI.27.10_1  361MOD11A2  29.732105
11404  Malawi    Thyolo       TA Nsabwe  MWI.27.11_1  361MOD11A2  32.759216
11405  Malawi    Thyolo       TA Thomas  MWI.27.12_1  361MOD11A2  30.449302
11406  Malawi    Thyolo     Thyolo Boma  MWI.27.13_1  361MOD11A2        NaN
11407  Malawi     Zomba     Lake Chilwa   MWI.28.1_1  361MOD11A2        NaN

[11408 rows x 6 columns]

In [70]:
# COMBINING LST


import os
import pandas as pd
import re
from datetime import datetime, timedelta

def combine_lst_datasets(input_dir='Datasets/GC_testRefined2', output_file='Datasets/GC_testRefined/combined_lst_data.csv'):
    """
    Improved version that:
    - Handles both MODIS and mean_ date formats
    - Returns consistent datetime objects
    - Fixes the date comparison error
    """
    lst_files = sorted([f for f in os.listdir(input_dir) if f.endswith('_lst.csv')])
    
    if not lst_files:
        print("No *_lst.csv files found")
        return
    
    print(f"Found {len(lst_files)} files to combine")
    
    all_data = []
    
    for year_offset, input_file in enumerate(lst_files):
        year = 2020 + year_offset
        
        try:
            file_path = os.path.join(input_dir, input_file)
            df = pd.read_csv(file_path)
            
            # Standardize column names
            df.columns = df.columns.str.strip()
            df = df.rename(columns={'ID_2': 'GID_2'})
            
            # Get ID columns
            id_vars = [col for col in ['NAME_0', 'NAME_1', 'NAME_2', 'GID_2'] 
                      if col in df.columns]
            
            # Melt the dataframe
            date_columns = [col for col in df.columns if col not in id_vars]
            df_melted = pd.melt(
                df,
                id_vars=id_vars,
                value_vars=date_columns,
                var_name='date_code',
                value_name='lst_value'
            )
            
            # Add metadata
            df_melted['year'] = year
            df_melted['source_file'] = input_file
            
            # Parse dates (now returns pd.Timestamp for consistency)
            df_melted['date'] = df_melted['date_code'].apply(
                lambda x: parse_modis_date(x, year)
            )
            
            all_data.append(df_melted)
            print(f"Processed {input_file} as year {year}")
            
        except Exception as e:
            print(f"Error processing {input_file}: {str(e)}")
            continue
    
    if not all_data:
        print("No files processed successfully")
        return
    
    combined_df = pd.concat(all_data, ignore_index=True)
    
    # Convert all dates to pd.Timestamp for consistent handling
    combined_df['date'] = pd.to_datetime(combined_df['date'])
    
    # Save combined data
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    combined_df.to_csv(output_file, index=False)
    
    # Print summary with proper date handling
    print("\nCombined data summary:")
    print(f"- Total rows: {len(combined_df)}")
    print(f"- Date range: {combined_df['date'].min().date()} to {combined_df['date'].max().date()}")
    print(f"- Unique locations: {combined_df['NAME_2'].nunique()}")
    print(f"\nSuccess! Saved to {output_file}")
    
    return combined_df

def parse_modis_date(date_code, year):
    """Improved date parser that returns pd.Timestamp"""
    if pd.isna(date_code):
        return pd.NaT
    
    date_code = str(date_code).strip()
    
    try:
        # Handle mean_MM.DD format
        if date_code.startswith('mean_'):
            month, day = map(int, date_code[5:].split('.'))
            return pd.Timestamp(year=year, month=month, day=day)
        
        # Handle DDDMOD... format (day of year)
        elif 'MOD' in date_code:
            day_of_year = int(date_code[:3])
            return pd.Timestamp(year=year, month=1, day=1) + pd.Timedelta(days=day_of_year-1)
        
        # Handle simple numeric (day of year)
        elif date_code.isdigit():
            day_of_year = int(date_code)
            return pd.Timestamp(year=year, month=1, day=1) + pd.Timedelta(days=day_of_year-1)
        
        return pd.NaT
    except Exception:
        return pd.NaT

# Run the processor
combine_lst_datasets()

Found 6 files to combine
Processed new2020_lst.csv as year 2020
Processed new2021_lst.csv as year 2021
Processed new2022_lst.csv as year 2022
Processed new2023_lst.csv as year 2023
Processed new2024_lst.csv as year 2024
Processed new2025_lst.csv as year 2025

Combined data summary:
- Total rows: 58102
- Date range: 2020-01-01 to 2025-03-06
- Unique locations: 234

Success! Saved to Datasets/GC_testRefined/combined_lst_data.csv

,NAME_0,NAME_1,NAME_2,GID_2,date_code,lst_value,year,source_file,date
0,Malawi,Balaka,Balaka Town,MWI.1.1_1,001MOD11A2,29.465000,2020,new2020_lst.csv,2020-01-01
1,Malawi,Balaka,TA Kalembo,MWI.1.2_1,001MOD11A2,28.482760,2020,new2020_lst.csv,2020-01-01
2,Malawi,Balaka,TA Nsamala,MWI.1.3_1,001MOD11A2,28.709750,2020,new2020_lst.csv,2020-01-01
3,Malawi,Blantyre,Blantyre City,MWI.2.1_1,001MOD11A2,24.961481,2020,new2020_lst.csv,2020-01-01
4,Malawi,Blantyre,TA Chigaru,MWI.2.2_1,001MOD11A2,30.762977,2020,new2020_lst.csv,2020-01-01
...,...,...,...,...,...,...,...,...,...
58097,Malawi,Ntchisi,TA Kasukula,MWI.23.7_1,mean_03.06,25.834746,2025,new2025_lst.csv,2025-03-06
58098,Malawi,Phalombe,Lake Chilwa,MWI.24.1_1,mean_03.06,24.195370,2025,new2025_lst.csv,2025-03-06
58099,Malawi,Phalombe,TA Mkhumba,MWI.24.2_1,mean_03.06,26.781043,2025,new2025_lst.csv,2025-03-06
58100,Malawi,Phalombe,TA Nazombe,MWI.24.3_1,mean_03.06,26.509004,2025,new2025_lst.csv,2025-03-06
58101,Malawi,Rumphi,Lake Malawi,MWI.25.1_1,mean_03.06,NaN,2025,new2025_lst.csv,2025-03-06

In [ ]:
# COMBINING NDFI

import os
import pandas as pd
import re
from datetime import datetime

def combine_ndvi_datasets(input_dir='Datasets/GC_testRefined2', output_file='Datasets/GC_testRefined/combined_ndvi_data.csv'):
    """
    Enhanced version that handles:
    - Multiple date formats (MOD13A2, mean_MM.DD, Mean_NDVI_YYYY.MM.DD)
    - Flexible column naming
    - Consistent datetime handling
    """
    ndvi_files = sorted([f for f in os.listdir(input_dir) if f.endswith('_ndvi.csv')])
    
    if not ndvi_files:
        print("No *_ndvi.csv files found")
        return
    
    print(f"Found {len(ndvi_files)} files to combine")
    
    all_data = []
    
    for year_offset, input_file in enumerate(ndvi_files):
        try:
            file_path = os.path.join(input_dir, input_file)
            df = pd.read_csv(file_path)
            
            # Standardize column names
            df.columns = df.columns.str.strip()
            df = df.rename(columns={'ID_2': 'GID_2'})
            
            # Get ID columns
            id_vars = [col for col in ['NAME_0', 'NAME_1', 'NAME_2', 'GID_2'] 
                      if col in df.columns]
            
            # Melt the dataframe
            date_columns = [col for col in df.columns if col not in id_vars]
            df_melted = pd.melt(
                df,
                id_vars=id_vars,
                value_vars=date_columns,
                var_name='date_code',
                value_name='ndvi_value'
            )
            
            # Parse dates - now handles multiple formats
            df_melted['date'] = df_melted['date_code'].apply(
                lambda x: parse_ndvi_date(x)
            )
            
            # Extract year from date (more reliable than file order)
            df_melted['year'] = df_melted['date'].dt.year
            
            df_melted['source_file'] = input_file
            all_data.append(df_melted)
            print(f"Processed {input_file}")
            
        except Exception as e:
            print(f"Error processing {input_file}: {str(e)}")
            continue
    
    if not all_data:
        print("No files processed successfully")
        return
    
    combined_df = pd.concat(all_data, ignore_index=True)
    
    # Final cleaning
    combined_df['date'] = pd.to_datetime(combined_df['date'])
    combined_df = combined_df.dropna(subset=['date'])  # Remove rows with invalid dates
    
    # Save combined data
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    combined_df.to_csv(output_file, index=False)
    
    # Print summary
    print("\nCombined data summary:")
    print(f"- Total rows: {len(combined_df)}")
    print(f"- Date range: {combined_df['date'].min().strftime('%Y-%m-%d')} to {combined_df['date'].max().strftime('%Y-%m-%d')}")
    print(f"- Unique locations: {combined_df['NAME_2'].nunique()}")
    print(f"- Date formats found: {combined_df['date_code'].str.extract(r'^([^0-9]+)')[0].unique()}")
    print(f"\nSuccess! Saved to {output_file}")
    
    return combined_df

def parse_ndvi_date(date_code):
    """Enhanced date parser for multiple NDVI date formats"""
    if pd.isna(date_code):
        return pd.NaT
    
    date_code = str(date_code).strip()
    
    try:
        # Handle Mean_NDVI_YYYY.MM.DD format
        if date_code.startswith('Mean_NDVI_'):
            return pd.to_datetime(date_code[10:], format='%Y.%m.%d')
        
        # Handle mean_MM.DD format
        elif date_code.startswith('mean_'):
            month, day = map(int, date_code[5:].split('.'))
            # Infer year from the date itself (if available in code)
            year_match = re.search(r'\d{4}', date_code)
            year = int(year_match.group(0)) if year_match else pd.NaT
            return pd.to_datetime(f"{year}.{month}.{day}", format='%Y.%m.%d', errors='coerce')
        
        # Handle DDDMOD... format (day of year)
        elif 'MOD' in date_code:
            day_of_year = int(date_code[:3])
            year_match = re.search(r'MOD(\d{2})', date_code)
            year = 2000 + int(year_match.group(1)) if year_match else pd.NaT
            return pd.to_datetime(f"{year}-{day_of_year}", format='%Y-%j') if not pd.isna(year) else pd.NaT
        
        # Handle simple numeric (day of year)
        elif date_code.isdigit():
            day_of_year = int(date_code)
            return pd.NaT  # Can't determine year from just day number
        
        return pd.NaT
    except Exception as e:
        print(f"Warning: Could not parse date code {date_code} - {str(e)}")
        return pd.NaT

# Run the processor
combine_ndvi_datasets()

Found 6 files to combine
Processed new2020_ndvi.csv
Processed new2021_ndvi.csv
Processed new2022_ndvi.csv
Processed new2023_ndvi.csv
Processed new2024_ndvi.csv
Processed new2025_ndvi.csv

Combined data summary:
- Total rows: 27938
- Date range: 2013-01-01 to 2025-02-18
- Unique locations: 227
- Date formats found: [nan 'Mean_NDVI_']

Success! Saved to Datasets/GC_testRefined/combined_ndvi_data.csv

,NAME_0,NAME_1,NAME_2,GID_2,date_code,ndvi_value,date,year,source_file
0,Malawi,Balaka,Balaka Town,MWI.1.1_1,001MOD13A2,0.622700,2013-01-01,2013,new2020_ndvi.csv
1,Malawi,Balaka,TA Kalembo,MWI.1.2_1,001MOD13A2,0.681652,2013-01-01,2013,new2020_ndvi.csv
2,Malawi,Balaka,TA Nsamala,MWI.1.3_1,001MOD13A2,0.755873,2013-01-01,2013,new2020_ndvi.csv
3,Malawi,Blantyre,Blantyre City,MWI.2.1_1,001MOD13A2,0.562132,2013-01-01,2013,new2020_ndvi.csv
4,Malawi,Blantyre,TA Chigaru,MWI.2.2_1,001MOD13A2,0.716399,2013-01-01,2013,new2020_ndvi.csv
...,...,...,...,...,...,...,...,...,...
27933,Malawi,Nsanje,SC Mbenje,MWI.21.4_1,Mean_NDVI_2025.02.18,0.645446,2025-02-18,2025,new2025_ndvi.csv
27934,Malawi,Nsanje,TA Chimombo,MWI.21.5_1,Mean_NDVI_2025.02.18,0.620370,2025-02-18,2025,new2025_ndvi.csv
27935,Malawi,Nsanje,TA Malemia,MWI.21.6_1,Mean_NDVI_2025.02.18,0.700370,2025-02-18,2025,new2025_ndvi.csv
27936,Malawi,Nsanje,TA Mlolo,MWI.21.7_1,Mean_NDVI_2025.02.18,0.697564,2025-02-18,2025,new2025_ndvi.csv
27937,Malawi,Nsanje,TA Ndamera,MWI.21.8_1,Mean_NDVI_2025.02.18,NaN,2025-02-18,2025,new2025_ndvi.csv

In [77]:
# combining rainfall:


import os
import pandas as pd
import re
from datetime import datetime

def combine_rainfall_datasets(input_dir='Datasets/GC_testRefined2', output_file='Datasets/GC_testRefined/combined_rainfall_data.csv'):
    """
    Processes all *_rainfall.csv files with:
    - Special handling for Mean_RAINFALL_YYYY.MM.DD[mm] format
    - Flexible column naming
    - Consistent datetime handling
    """
    rainfall_files = sorted([f for f in os.listdir(input_dir) if f.endswith('_rainfall.csv')])
    
    if not rainfall_files:
        print("No *_rainfall.csv files found")
        return
    
    print(f"Found {len(rainfall_files)} files to combine")
    
    all_data = []
    
    for input_file in rainfall_files:
        try:
            file_path = os.path.join(input_dir, input_file)
            df = pd.read_csv(file_path)
            
            # Standardize column names
            df.columns = df.columns.str.strip()
            df = df.rename(columns={'ID_2': 'GID_2'})
            
            # Get ID columns
            id_vars = [col for col in ['NAME_0', 'NAME_1', 'NAME_2', 'GID_2'] 
                      if col in df.columns]
            
            # Melt the dataframe
            date_columns = [col for col in df.columns if col not in id_vars]
            df_melted = pd.melt(
                df,
                id_vars=id_vars,
                value_vars=date_columns,
                var_name='date_code',
                value_name='rainfall_mm'  # Changed to reflect rainfall data
            )
            
            # Parse dates with specialized rainfall format handling
            df_melted['date'] = df_melted['date_code'].apply(
                lambda x: parse_rainfall_date(x)
            )
            
            # Extract year from the date itself
            df_melted['year'] = df_melted['date'].dt.year
            df_melted['source_file'] = input_file
            all_data.append(df_melted)
            print(f"Processed {input_file}")
            
        except Exception as e:
            print(f"Error processing {input_file}: {str(e)}")
            continue
    
    if not all_data:
        print("No files processed successfully")
        return
    
    combined_df = pd.concat(all_data, ignore_index=True)
    
    # Final cleaning
    combined_df['date'] = pd.to_datetime(combined_df['date'])
    combined_df = combined_df.dropna(subset=['date'])  # Remove rows with invalid dates
    
    # Save combined data
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    combined_df.to_csv(output_file, index=False)
    
    # Print summary
    print("\nCombined data summary:")
    print(f"- Total rows: {len(combined_df)}")
    print(f"- Date range: {combined_df['date'].min().strftime('%Y-%m-%d')} to {combined_df['date'].max().strftime('%Y-%m-%d')}")
    print(f"- Unique locations: {combined_df['NAME_2'].nunique()}")
    print(f"- Date formats found: {combined_df['date_code'].str.extract(r'^([^0-9]+)')[0].unique()}")
    print(f"\nSuccess! Saved to {output_file}")
    
    return combined_df

def parse_rainfall_date(date_code):
    """Specialized date parser for rainfall data formats"""
    if pd.isna(date_code):
        return pd.NaT
    
    date_code = str(date_code).strip()
    
    try:
        # Handle Mean_RAINFALL_YYYY.MM.DD[mm] format
        if date_code.startswith('Mean_RAINFALL_'):
            # Extract just the date part before [mm]
            date_part = date_code.split('[')[0][14:]
            return pd.to_datetime(date_part, format='%Y.%m.%d')
        
        # Handle other potential formats (add as needed)
        elif date_code.startswith('mean_'):
            month, day = map(int, date_code[5:].split('.'))
            year_match = re.search(r'\d{4}', date_code)
            year = int(year_match.group(0)) if year_match else pd.NaT
            return pd.to_datetime(f"{year}.{month}.{day}", format='%Y.%m.%d', errors='coerce')
        
        # Handle MODIS-style formats if present
        elif 'MOD' in date_code:
            day_of_year = int(date_code[:3])
            year_match = re.search(r'MOD(\d{2})', date_code)
            year = 2000 + int(year_match.group(1)) if year_match else pd.NaT
            return pd.to_datetime(f"{year}-{day_of_year}", format='%Y-%j') if not pd.isna(year) else pd.NaT
        
        return pd.NaT
    except Exception as e:
        print(f"Warning: Could not parse date code {date_code} - {str(e)}")
        return pd.NaT


combine_rainfall_datasets()

Found 4 files to combine
Processed new2022_rainfall.csv
Processed new2023_rainfall.csv
Processed new2024_rainfall.csv
Processed new2025_rainfall.csv

Combined data summary:
- Total rows: 290765
- Date range: 2022-01-01 to 2025-02-28
- Unique locations: 239
- Date formats found: ['Mean_RAINFALL_']

Success! Saved to Datasets/GC_testRefined/combined_rainfall_data.csv

,NAME_0,NAME_1,NAME_2,GID_2,date_code,rainfall_mm,date,year,source_file
0,Malawi,Balaka,Balaka Town,MWI.1.1_1,Mean_RAINFALL_2022.01.01[mm],NaN,2022-01-01,2022,new2022_rainfall.csv
1,Malawi,Balaka,TA Kalembo,MWI.1.2_1,Mean_RAINFALL_2022.01.01[mm],19.954455,2022-01-01,2022,new2022_rainfall.csv
2,Malawi,Balaka,TA Nsamala,MWI.1.3_1,Mean_RAINFALL_2022.01.01[mm],20.860708,2022-01-01,2022,new2022_rainfall.csv
3,Malawi,Blantyre,Blantyre City,MWI.2.1_1,Mean_RAINFALL_2022.01.01[mm],20.623785,2022-01-01,2022,new2022_rainfall.csv
4,Malawi,Blantyre,TA Chigaru,MWI.2.2_1,Mean_RAINFALL_2022.01.01[mm],12.332400,2022-01-01,2022,new2022_rainfall.csv
...,...,...,...,...,...,...,...,...,...
290760,Malawi,Thyolo,TA Nsabwe,MWI.27.11_1,Mean_RAINFALL_2025.02.28[mm],4.498106,2025-02-28,2025,new2025_rainfall.csv
290761,Malawi,Thyolo,TA Thomas,MWI.27.12_1,Mean_RAINFALL_2025.02.28[mm],2.823164,2025-02-28,2025,new2025_rainfall.csv
290762,Malawi,Thyolo,Thyolo Boma,MWI.27.13_1,Mean_RAINFALL_2025.02.28[mm],NaN,2025-02-28,2025,new2025_rainfall.csv
290763,Malawi,Zomba,Lake Chilwa,MWI.28.1_1,Mean_RAINFALL_2025.02.28[mm],9.322730,2025-02-28,2025,new2025_rainfall.csv
290764,Malawi,Zomba,SC Mbiza,MWI.28.2_1,Mean_RAINFALL_2025.02.28[mm],NaN,2025-02-28,2025,new2025_rainfall.csv

In [8]:
import os
import csv
import re

def clean_daily_temp_files_preserve_columns(input_dir='Datasets/Daily_temp', output_dir='Datasets/Daily_tempRefined2'):
    """
    Processes daily temperature files while preserving ALL columns:
    - Skips first 216 rows
    - Removes last row
    - Adds NAME_2 as FIRST column
    - Preserves original headers exactly
    - Saves as [RegionName].csv
    """
    # Create output directory if needed
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all matching files
    temp_files = [f for f in os.listdir(input_dir) 
                 if f.startswith('daily_mean_temperature_') and f.endswith('.csv')]
    
    if not temp_files:
        print("No daily_mean_temperature_*.csv files found")
        return
    
    print(f"Found {len(temp_files)} files to process")
    
    for input_file in temp_files:
        try:
            # Extract region name from filename
            region_match = re.search(r'daily_mean_temperature_(.+)\.csv$', input_file)
            if not region_match:
                print(f"Skipping invalid filename: {input_file}")
                continue
                
            region_name = region_match.group(1).strip()
            output_file = f"{region_name}.csv"
            output_path = os.path.join(output_dir, output_file)
            
            print(f"\nProcessing {input_file} -> {output_file}")
            
            # Read original header (row 216)
            with open(os.path.join(input_dir, input_file), 'r', encoding='utf-8', errors='ignore') as f:
                reader = csv.reader(f)
                for _ in range(216):  # Skip to row 216
                    header = next(reader)
            
            # Process data rows
            cleaned_rows = []
            with open(os.path.join(input_dir, input_file), 'r', encoding='utf-8', errors='ignore') as f:
                reader = csv.reader(f)
                
                # Skip initial 216 rows
                for _ in range(216):
                    next(reader)
                
                # Read all rows except last
                rows = list(reader)
                if rows:
                    cleaned_rows = rows[:-1]
            
            # Modify headers - add NAME_2 as first column
            if header:
                new_header = ['NAME_2'] + header
                cleaned_rows.insert(0, new_header)  # Insert headers at start
                
                # Add region_name to each data row as first column
                for i in range(1, len(cleaned_rows)):
                    cleaned_rows[i] = [region_name] + cleaned_rows[i]
            
            # Write cleaned data
            with open(output_path, 'w', newline='', encoding='utf-8') as f:
                writer = csv.writer(f)
                writer.writerows(cleaned_rows)
            
            print(f"Successfully processed {input_file}")
            print(f"Original columns: {header}")
            print(f"New columns: {new_header}")
            
        except Exception as e:
            print(f"Error processing {input_file}: {str(e)}")
    
    print("\nBatch processing complete!")

# Run the cleaner
clean_daily_temp_files_preserve_columns(input_dir='Datasets/Daily_temp')

Found 25 files to process

Processing daily_mean_temperature_Kasungu National Park.csv -> Kasungu National Park.csv
Successfully processed daily_mean_temperature_Kasungu National Park.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_Lake Malawi.csv -> Lake Malawi.csv
Successfully processed daily_mean_temperature_Lake Malawi.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_Lengwe National Park.csv -> Lengwe National Park.csv
Successfully processed daily_mean_temperature_Lengwe National Park.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_Lilongwe City.csv -> Lilongwe City.csv
Successfully processed daily_mean_temperature_Lilongwe City.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_Nyika N.P. - Chitipa.csv -> Nyika N.P. - Chitipa.csv
Successfully processed daily_mean_temperature_Nyika N.P. - Chitipa.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_SC Dambe.csv -> SC Dambe.csv
Successfully processed daily_mean_temperature_SC Dambe.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_SC Kampingo Sibande.csv -> SC Kampingo Sibande.csv
Successfully processed daily_mean_temperature_SC Kampingo Sibande.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_SC Khosolo Gwaza Jere.csv -> SC Khosolo Gwaza Jere.csv
Successfully processed daily_mean_temperature_SC Khosolo Gwaza Jere.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_SC Mbwana Nyambi.csv -> SC Mbwana Nyambi.csv
Successfully processed daily_mean_temperature_SC Mbwana Nyambi.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Chigaru.csv -> TA Chigaru.csv
Successfully processed daily_mean_temperature_TA Chigaru.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Chikulamayembe.csv -> TA Chikulamayembe.csv
Successfully processed daily_mean_temperature_TA Chikulamayembe.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Dzoole.csv -> TA Dzoole.csv
Successfully processed daily_mean_temperature_TA Dzoole.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Kameme.csv -> TA Kameme.csv
Successfully processed daily_mean_temperature_TA Kameme.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Kasumbu.csv -> TA Kasumbu.csv
Successfully processed daily_mean_temperature_TA Kasumbu.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Kawinga.csv -> TA Kawinga.csv
Successfully processed daily_mean_temperature_TA Kawinga.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Kyungu.csv -> TA Kyungu.csv
Successfully processed daily_mean_temperature_TA Kyungu.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Mabuka.csv -> TA Mabuka.csv
Successfully processed daily_mean_temperature_TA Mabuka.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Mponda.csv -> TA Mponda.csv
Successfully processed daily_mean_temperature_TA Mponda.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Mwambo.csv -> TA Mwambo.csv
Successfully processed daily_mean_temperature_TA Mwambo.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Mzikubola.csv -> TA Mzikubola.csv
Successfully processed daily_mean_temperature_TA Mzikubola.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Ngabu.csv -> TA Ngabu.csv
Successfully processed daily_mean_temperature_TA Ngabu.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Nsamala.csv -> TA Nsamala.csv
Successfully processed daily_mean_temperature_TA Nsamala.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Pemba.csv -> TA Pemba.csv
Successfully processed daily_mean_temperature_TA Pemba.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Thomas.csv -> TA Thomas.csv
Successfully processed daily_mean_temperature_TA Thomas.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Processing daily_mean_temperature_TA Wimbe.csv -> TA Wimbe.csv
Successfully processed daily_mean_temperature_TA Wimbe.csv
Original columns: ['DATE', 'Mean Temperature', 'YEAR']
New columns: ['NAME_2', 'DATE', 'Mean Temperature', 'YEAR']

Batch processing complete!